pipeline {
    agent any

    environment {
        GIT_CREDENTIALS_ID = 'your-jenkins-github-credentials-id' // Replace with your Jenkins GitHub credentials ID
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: "${env.GIT_CREDENTIALS_ID}", url: 'https://github.com/stepholo/alx-backend-python.git', branch: 'main'
            }
        }
        stage('Install Dependencies') {
            steps {
                dir('messaging_app') {
                    sh 'python -m venv ${VENV_DIR}'
                    sh './${VENV_DIR}/bin/pip install --upgrade pip'
                    sh './${VENV_DIR}/bin/pip install -r requirements.txt'
                    sh './${VENV_DIR}/bin/pip install pytest pytest-html'
                }
            }
        }
        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh './${VENV_DIR}/bin/pytest --html=pytest_report.html'
                }
            }
        }
    }
    post {
        always {
            dir('messaging_app') {
                archiveArtifacts artifacts: 'pytest_report.html', fingerprint: true
                junit '**/test-results.xml'
            }
        }
    }
}